apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: minecraft
  namespace: default

repo: https://itzg.github.io/minecraft-server-charts
name: minecraft
version: 3.1.3
releaseName: example
includeCRDs: false
valuesInline:
  minecraftServer:
    eula: true
    difficulty: hard
    rcon:
        enabled: true
